# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolhost < Formula
  desc "One governed front door between your agent and your MCP servers"
  homepage "https://github.com/gettoolhost/toolhost-local"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.3/toolhost_darwin_amd64.tar.gz"
      sha256 "b32318217f6c85840f030f714b62a83466c91fe1ab5b831d2995fae51beeca4f"

      define_method(:install) do
        bin.install "toolhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.3/toolhost_darwin_arm64.tar.gz"
      sha256 "4f7cd74e8092708fe24e68597b0d99c1032dedfe3b6fe2d0e4b69ecb7861f842"

      define_method(:install) do
        bin.install "toolhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.3/toolhost_linux_amd64.tar.gz"
      sha256 "fb455fee5de27a525db8484636c442a0ab95f6b6573116bcca2c232d343f24b4"
      define_method(:install) do
        bin.install "toolhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.3/toolhost_linux_arm64.tar.gz"
      sha256 "a4fe0a8728594c159171216c3fc4ce81a77791588fba564af3e72dcb37761ee8"
      define_method(:install) do
        bin.install "toolhost"
      end
    end
  end

  test do
    system "#{bin}/toolhost", "version"
  end
end
