# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Toolhost < Formula
  desc "One governed front door between your agent and your MCP servers"
  homepage "https://github.com/gettoolhost/toolhost-local"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.1/toolhost_darwin_amd64.tar.gz"
      sha256 "aa56775469fce7462a37245b405c7054e9c2ed838266722b6379420db0282c7d"

      define_method(:install) do
        bin.install "toolhost"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.1/toolhost_darwin_arm64.tar.gz"
      sha256 "22e75f91cd53b907cb06ceeef535f46f00da06dc0dd345c43eda6a1a74b728df"

      define_method(:install) do
        bin.install "toolhost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.1/toolhost_linux_amd64.tar.gz"
      sha256 "e9b37276bbb637e690dc67e0274601da764d5657989d4d366a55bdec1e6d02c3"
      define_method(:install) do
        bin.install "toolhost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gettoolhost/toolhost-local/releases/download/v0.0.1/toolhost_linux_arm64.tar.gz"
      sha256 "daaaacc5515acdf535f4ecc31dc0d78db6f89fa017647fe4bf206a62d353048c"
      define_method(:install) do
        bin.install "toolhost"
      end
    end
  end

  test do
    system "#{bin}/toolhost", "version"
  end
end
